Add Downgrade com.android.tools.build:gradle to v8.7.0
Nightly build fails:

```
2024-10-03 23:18:19,270 INFO: APK file was successfully validated!
2024-10-03 23:18:19,321 CRITICAL: Unknown exception found!
Traceback (most recent call last):
 File "/usr/local/lib/python3.10/dist-packages/androguard/core/bytecodes/apk.py", line 1556, in get_android_resources
 return self.arsc["resources.arsc"]
KeyError: 'resources.arsc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/usr/local/bin/fdroid", line 8, in <module>
 sys.exit(main())
 File "/usr/local/lib/python3.10/dist-packages/fdroidserver/__main__.py", line 230, in main
 raise e
...
 File "/usr/local/lib/python3.10/dist-packages/androguard/core/bytecodes/axml/__init__.py", line 2181, in __init__
 raise ResParserError("res1 must be zero!")
androguard.core.bytecodes.axml.ResParserError: res1 must be zero!
```

This reverts commit b8bf1200c162e17f70d86880f7c5ab692a3c52f2. patch - d34dcb6fc6dd456df3ef93076d9aecb0963ffd29